Enable channel-first and video support in RandomResizedCrop.
NVIDIA/DALI pull request #2430
Opened 2020-11-03 11:31 UTC by mzient

Signed-off-by: Michał Zientkiewicz <mzient@gmail.com>

#### Why we need this PR?
*Pick one, remove the rest*
- It fixes a bug *bug description*
- It adds new feature needed because of *why we need this feature*
- Refactoring to improve *what*

#### What happened in this PR?
*Fill relevant points, put NA otherwise. Replace anything inside []*
 - What solution was applied:
     * Handle index of the first spatial dimension
     * Add more allowed layouts
     * Remove the check for the number of dimensions (it's implicitly handled by layout check).
 - Affected modules and functionalities:
     * RandomResizedCrop
 - Key points relevant for the review:
     * N/A
 - Validation and testing:
     * Checked manually, but the underlying machinery is tested in video resize test.
 - Documentation (including examples):
     * N/A (added AllowSequences)

**JIRA TASK**: DALI-1720

2020-11-03 11:32 UTC, JanuszL requested changes
Please add a relevant test.

2020-11-03 11:46 UTC, mzient commented
Take it or leave it.

2020-11-03 15:33 UTC, mzient commented
!build

2020-11-03 15:38 UTC, dali-automaton commented
**CI MESSAGE**: [1758438]: BUILD STARTED

2020-11-03 17:19 UTC, dali-automaton commented
**CI MESSAGE**: [1758438]: BUILD PASSED

2020-11-03 18:05 UTC, JanuszL approved these changes

2020-11-04 07:39 UTC, jantonguirao approved these changes

2020-11-04 07:39 UTC, jantonguirao commented on dali/test/python/test_operator_random_resized_crop.py
> +        h, w = input_shape[hidx:hidx+2]
nitpick:
inconsistent with line 50? Maybe unify?

2020-11-04 07:40 UTC, merged