Update tensorflow in conda
NVIDIA/DALI pull request #3471
Opened 2021-11-04 13:56 UTC by szalpal

Signed-off-by: szalpal <mszolucha@nvidia.com>

## Description
- [ ] **Bug fix** (*non-breaking change which fixes an issue*)
- [ ] **New feature** (*non-breaking change which adds functionality*)
- [ ] **Breaking change** (*fix or feature that would cause existing functionality to not work as expected*)
- [ ] **Refactoring** (*Redesign of existing code that doesn't affect functionality*)
- [ ] **Other** (*e.g. Documentation, Tests, Configuration*)

### What happened in this PR

#### Additional information
- Affected modules and functionalities:

- Key points relevant for the review:

## Checklist

### Tests
- [ ] Existing tests apply
- [ ] New tests added
  - [ ] Python tests
  - [ ] GTests
  - [ ] Benchmark
  - [ ] Other
- [ ] N/A

### Documentation
- [ ] Existing documentation applies
- [ ] Documentation updated
  - [ ] Docstring
  - [ ] Doxygen
  - [ ] RST
  - [ ] Jupyter
  - [ ] Other
- [ ] N/A

### DALI team only

#### Requirements
- [ ] Implements new requirements
- [ ] Affects existing requirements
- [ ] N/A

**REQ IDs**: N/A

**JIRA TASK**: N/A

2021-11-04 14:00 UTC, JanuszL approved these changes

2021-11-04 17:52 UTC, dali-automaton commented
**CI MESSAGE**: [3334242]: BUILD STARTED

2021-11-04 18:55 UTC, JanuszL requested changes
It fails for python 3.6 in conda.

2021-11-04 19:18 UTC, dali-automaton commented
**CI MESSAGE**: [3334242]: BUILD FAILED

2021-11-04 20:21 UTC, JanuszL commented
Even leaving the TF version blank fails the job if the protobuf is suppose to be at least 3.19. Maybe we should revert protobuf changes (conda will pick up the latest compatible anyway).
I would leave a comment why we are doing so.

2021-11-05 16:03 UTC, dali-automaton commented
**CI MESSAGE**: [3340595]: BUILD STARTED

2021-11-05 17:54 UTC, mzient approved these changes

2021-11-05 17:58 UTC, JanuszL approved these changes

2021-11-05 18:22 UTC, dali-automaton commented
**CI MESSAGE**: [3340595]: BUILD FAILED

2021-11-05 18:36 UTC, dali-automaton commented
**CI MESSAGE**: [3341532]: BUILD STARTED

2021-11-06 01:03 UTC, dali-automaton commented
**CI MESSAGE**: [3343795]: BUILD STARTED

2021-11-06 04:54 UTC, dali-automaton commented
**CI MESSAGE**: [3343795]: BUILD PASSED

2021-11-06 07:56 UTC, merged