ShapeToRoi implementation with STL
NVIDIA/DALI pull request #4375
Opened 2022-10-20 08:35 UTC by szalpal

Signed-off-by: szalpal <mszolucha@nvidia.com>

## Category:

## Description:

## Additional information:

### Affected modules and functionalities:

### Key points relevant for the review:

### Tests:

- [ ] Existing tests apply
- [ ] New tests added
  - [ ] Python tests
  - [ ] GTests
  - [ ] Benchmark
  - [ ] Other
- [ ] N/A

## Checklist

### Documentation
- [ ] Existing documentation applies
- [ ] Documentation updated
  - [ ] Docstring
  - [ ] Doxygen
  - [ ] RST
  - [ ] Jupyter
  - [ ] Other
- [ ] N/A

### DALI team only

#### Requirements
- [ ] Implements new requirements
- [ ] Affects existing requirements
- [ ] N/A

**REQ IDs**: N/A

**JIRA TASK**: N/A

2022-10-20 08:37 UTC, szalpal commented
!build

2022-10-20 08:40 UTC, dali-automaton commented
**CI MESSAGE**: [6239450]: BUILD STARTED

2022-10-20 10:17 UTC, dali-automaton commented
**CI MESSAGE**: [6239450]: BUILD PASSED

2022-10-20 14:58 UTC, banasraf approved these changes

2022-10-25 06:47 UTC, mzient commented on dali/kernels/imgproc/roi.h
>    return ret;
```suggestion
return vec2shape(roi.extent());
```
...and please don't use STL in vec2shape, since it needs to be `__device__` compatible.

2022-10-25 06:49 UTC, mzient requested changes
Use vec2shape.

2022-11-15 01:44 UTC, szalpal commented
Closing, since this change is unnecessary

2022-11-15 01:44 UTC, closed without merging