Fix access to unitialized memory in RNG ops
NVIDIA/DALI pull request #5394
Opened 2024-03-25 20:48 UTC by klecki

Operator used vector of reintereted bytes with assignment of std::distribution object carrying some state.
Switch to a vector so the copy and move are not UB.

## Category:

## Description:

## Additional information:

### Affected modules and functionalities:

### Key points relevant for the review:

### Tests:

- [ ] Existing tests apply
- [ ] New tests added
  - [ ] Python tests
  - [ ] GTests
  - [ ] Benchmark
  - [ ] Other
- [ ] N/A

## Checklist

### Documentation
- [ ] Existing documentation applies
- [ ] Documentation updated
  - [ ] Docstring
  - [ ] Doxygen
  - [ ] RST
  - [ ] Jupyter
  - [ ] Other
- [ ] N/A

### DALI team only

#### Requirements
- [ ] Implements new requirements
- [ ] Affects existing requirements
- [ ] N/A

**REQ IDs**: N/A

**JIRA TASK**: N/A

2024-03-25 20:50 UTC, dali-automaton commented
**CI MESSAGE**: [13784528]: BUILD STARTED

2024-03-26 03:16 UTC, dali-automaton commented
**CI MESSAGE**: [13784528]: BUILD FAILED

2024-03-26 10:30 UTC, klecki commented on dali/operators/random/rng_base_cpu.h
> +  std::vector<Dist> dists(nsamples);
This is just a batch of the default constructed objects, which should be cheap, and we still reassign them in every iteration in most cases. Based on this I thought it should be ok.

2024-03-26 10:39 UTC, JanuszL approved these changes

2024-03-26 11:46 UTC, stiepan approved these changes

2024-03-26 15:23 UTC, mzient commented on dali/operators/random/rng_base_cpu.h
> +  std::vector<Dist> dists(nsamples);
This is captured by value.

2024-03-26 15:24 UTC, mzient requested changes
Please capture the distribution vector by reference or return to the use of a pointer.

2024-03-26 15:31 UTC, klecki commented
Same fix with less allocations reimplemented in #5395

2024-03-26 15:31 UTC, closed without merging